aiad:
    resource: "@AiadBundle/Controller/"
    type:     annotation
    prefix:   /
login:
    path: /login
    defaults: { _controller: AiadBundle:Login:login }

login_check:
    path: /login_check

logout:
    path: /logout