security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        AiadBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:
        ROLE_SUPER_ADMIN: [ROLE_SUPERADMIN, ROLE_ADMIN, ROLE_OPERATOR, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        my_entity_provider:
            entity:
                class:              AiadBundle:User
#                property:           username

    firewalls:

        default:
                pattern: /.*
                provider: my_entity_provider
                anonymous: ~
                http_basic: ~
                form_login:
                    login_path: /login
                    check_path: /login_check
                    always_use_default_target_path: true
                    default_target_path: /

                logout:
                    path:   /logout
                    target: /
                    invalidate_session: false

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/welcome, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/konfigurime, roles: ROLE_ADMIN }